-- Acceso seguro de SOLO LECTURA para el bot Discord (rol anon).
-- Ejecutar en Supabase SQL Editor (Production) UNA vez.
--
-- No expone tokens ni api_key: solo columnas públicas vía RPC SECURITY DEFINER.
-- Realtime: tabla discord_link_events (sin secretos) + publicación.

-- ─── /cuenta y listados ───────────────────────────────────────────────────────

DROP FUNCTION IF EXISTS public.bot_get_user_by_discord_id(text);

CREATE FUNCTION public.bot_get_user_by_discord_id(p_discord_id text)
RETURNS TABLE (
  user_id text,
  login text,
  display_name text,
  role text,
  is_active boolean,
  timezone text,
  profile_image_url text,
  last_active timestamptz,
  discord_id text,
  custom_rate_limit integer,
  custom_cache_ttl integer
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    u.user_id::text,
    u.login::text,
    COALESCE(u.display_name, u.login)::text,
    COALESCE(u.role::text, 'default'),
    COALESCE(u.is_active, true),
    COALESCE(u.timezone, 'UTC')::text,
    u.profile_image_url::text,
    u.last_active,
    u.discord_id::text,
    u.custom_rate_limit::integer,
    u.custom_cache_ttl::integer
  FROM public.users u
  WHERE u.discord_id = p_discord_id
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.bot_list_discord_links()
RETURNS TABLE (
  discord_id text,
  login text,
  display_name text,
  discord_linked_at timestamptz
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    u.discord_id::text,
    u.login::text,
    COALESCE(u.display_name, u.login)::text,
    u.discord_linked_at
  FROM public.users u
  WHERE u.discord_id IS NOT NULL;
$$;

REVOKE ALL ON FUNCTION public.bot_get_user_by_discord_id(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.bot_list_discord_links() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.bot_get_user_by_discord_id(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.bot_list_discord_links() TO anon, authenticated;

-- ─── Eventos Realtime (sin secretos) ───────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.discord_link_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event text NOT NULL CHECK (event IN ('linked', 'unlinked')),
  discord_id text NOT NULL,
  login text,
  display_name text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS discord_link_events_created_at_idx
  ON public.discord_link_events (created_at DESC);

ALTER TABLE public.discord_link_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS discord_link_events_select_anon ON public.discord_link_events;
CREATE POLICY discord_link_events_select_anon
  ON public.discord_link_events
  FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE OR REPLACE FUNCTION public.notify_discord_link_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'UPDATE' AND OLD.discord_id IS DISTINCT FROM NEW.discord_id THEN
    IF OLD.discord_id IS NOT NULL THEN
      INSERT INTO public.discord_link_events (event, discord_id, login, display_name)
      VALUES (
        'unlinked',
        OLD.discord_id,
        OLD.login,
        COALESCE(OLD.display_name, OLD.login)
      );
    END IF;
    IF NEW.discord_id IS NOT NULL THEN
      INSERT INTO public.discord_link_events (event, discord_id, login, display_name)
      VALUES (
        'linked',
        NEW.discord_id,
        NEW.login,
        COALESCE(NEW.display_name, NEW.login)
      );
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS users_discord_link_events ON public.users;
CREATE TRIGGER users_discord_link_events
  AFTER UPDATE OF discord_id ON public.users
  FOR EACH ROW
  EXECUTE FUNCTION public.notify_discord_link_change();

-- Publicación Realtime (ignorar error si ya está)
DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.discord_link_events;
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Refrescar caché de PostgREST para que el bot vea los RPCs al instante
NOTIFY pgrst, 'reload schema';
